Repository SpartaEnergizerTeam/movie-site, pull requests merged in 2024-05, with the labels that each got.

#6 feat: 기본 구조 추가
  .gitignore
  README.md
  css/common.css
  css/index.css
  css/reset.css
  index.html
  js/index.js
Labels: enhancement

#15 feat : 랜덤 프로필 페이지
  css/profile.css
  js/profile.js
  profile.html
Labels: enhancement

#9 feat: 영화 댓글 작성하기 기능 구현
  css/review.css
  img/detail/star-fill.svg
  img/detail/star-half.svg
  img/detail/user.png
  js/review/index.js
  js/review/reviewForm/addReviewToLocalStorage.js
  js/review/reviewForm/isValidReviewValues.js
  js/review/reviewForm/reviewFormSubmitHandler.js
  js/review/reviewForm/reviewRatingClickHandler.js
  js/review/reviewList/getMovieReviews.js
  js/review/reviewList/renderMovieReviews.js
  js/review/utils.js
  js/utils/getUrlParamValue.js
  js/utils/localStorage.js
  review.html
Labels: enhancement

#23 feat: 댓글 삭제 구현
  css/common.css
  css/review.css
  img/detail/star-fill.svg
  img/detail/star-half.svg
  js/review/index.js
  js/review/reviewForm/deleteReviewHandler.js
  js/review/reviewForm/isValidReviewValues.js
  js/review/reviewForm/starRatingHandler.js
  js/review/reviewForm/useDeleteModal.js
  js/review/reviewForm/utils.js
  js/review/reviewForm/writeReviewHandler.js
  js/review/reviewList/renderMovieReviews.js
  js/review/utils.js
  review.html
Labels: enhancement

#27 feat: 댓글 수정 구현
  css/review.css
  js/review/index.js
  js/review/reviewForm/deleteReviewHandler.js
  js/review/reviewForm/editReviewHandler.js
  js/review/reviewForm/isValidReviewValues.js
  js/review/reviewForm/starRatingHandler.js
  js/review/reviewForm/useDeleteModal.js
  js/review/reviewForm/useModal.js
  js/review/reviewForm/utils.js
  js/review/reviewForm/writeReviewHandler.js
  js/review/reviewList/renderMovieReviews.js
  js/review/utils.js
  review.html
Labels: enhancement

#25 feat : 메인페이지 구현
  css/common.css
  css/index.css
  css/swiper-bundle.min.css
  img/favicon.ico
  img/main/arrow-left.png
  img/main/arrow-more.svg
  img/main/arrow-right.png
  img/main/icon-search.svg
  img/main/pause.svg
  img/main/play.svg
  img/main/rate-num/1.png
  img/main/rate-num/10.png
  img/main/rate-num/11.png
  img/main/rate-num/12.png
  img/main/rate-num/13.png
  img/main/rate-num/14.png
  img/main/rate-num/15.png
  img/main/rate-num/16.png
  img/main/rate-num/17.png
  img/main/rate-num/18.png
  img/main/rate-num/19.png
  img/main/rate-num/2.png
  img/main/rate-num/20.png
  img/main/rate-num/3.png
  img/main/rate-num/4.png
  img/main/rate-num/5.png
  img/main/rate-num/6.png
  img/main/rate-num/7.png
  img/main/rate-num/8.png
  img/main/rate-num/9.png
  img/main/swiper_next.png
  img/main/swiper_previous.png
  index.html
  js/api.js
  js/index.js
  js/swiper-bundle.min.js
Labels: enhancement

#24 Feature/상세페이지 구현
  css/detail.css
  detail.html
  img/detail/1713512289000104275.webp
  img/detail/detail_gra_bg.png
  img/detail/element-icon-share.svg
  js/api.js
  js/detail.js
Labels: enhancement

#32 feat: header와 검색페이지 구현
  css/common.css
  css/header.css
  css/index.css
  css/search-result.css
  css/search.css
  detail.html
  header.html
  img/common/ci-wavve.svg
  img/common/icon-alert.svg
  img/common/icon-search.svg
  img/common/search-delete.svg
  img/common/xbutton.svg
  index.html
  js/api.js
  js/common.js
  js/detail.js
  js/index.js
  js/searchList.js
  js/searchMain.js
  js/utils/getUrlParamValue.js
  search-result.html
  search.html
Labels: enhancement

#36 feat: html header 병합
  css/common.css
  css/detail.css
  css/header.css
  css/index.css
  css/profile.css
  detail.html
  header.html
  index.html
  js/common.js
  js/index.js
  profile.html
  search-result.html
  search.html
Labels: enhancement

#39 feat: 카테고리 호버시 하위 메뉴 노출
  css/common.css
  detail.html
  index.html
  search-result.html
  search.html
  subpage/nowplaying.html
  subpage/popular.html
  subpage/top20.html
  subpage/upcoming.html
Labels: enhancement

#41 refactor: 다크모드 디테일 수정
  css/common.css
  css/detail.css
  css/index.css
  css/reset.css
  css/review.css
  css/subpage.css
  detail.html
  index.html
  js/renderMovieDisplay.js
  js/review/utils.js
  search-result.html
  search.html
  subpage/nowplaying.html
  subpage/popular.html
  subpage/top20.html
  subpage/upcoming.html
Labels: enhancement

#42 feat: 허용되지 않은 페이지 접속시 alert
  css/review.css
  detail.html
  index.html
  js/common.js
  search-result.html
  search.html
  subpage/nowplaying.html
  subpage/popular.html
  subpage/top20.html
  subpage/upcoming.html
Labels: enhancement

#43 refactor: 폴더 구조 변경 및 footer 다크모드 반영
  css/page/detail.css
  css/page/footer.css
  css/page/profile.css
  css/page/review.css
  css/page/search-result.css
  css/page/search.css
  css/page/subpage.css
  img/common/ico-footer-wavve.svg
  index.html
  js/common.js
  js/index.js
  js/page/detail.js
  js/page/profile.js
  js/page/review/index.js
  js/page/review/reviewForm/deleteReviewHandler.js
  js/page/review/reviewForm/editReviewHandler.js
  js/page/review/reviewForm/isValidReviewValues.js
  js/page/review/reviewForm/starRatingHandler.js
  js/page/review/reviewForm/useModal.js
  js/page/review/reviewForm/utils.js
  js/page/review/reviewForm/writeReviewHandler.js
  js/page/review/reviewList/getMovieReviews.js
  js/page/review/reviewList/renderMovieReviews.js
  js/page/review/utils.js
  js/page/searchList.js
  js/page/searchMain.js
  js/page/subpage.js
  js/renderMovieDisplay.js
  page/detail.html
  page/nowplaying.html
  page/popular.html
  page/profile.html
  page/search-result.html
  page/search.html
  page/top20.html
  page/upcoming.html
Labels: enhancement

#45 fix: 경로 오류 수정
  js/page/detail.js
  js/page/profile.js
  js/page/review/reviewForm/writeReviewHandler.js
Labels: bug

#46 merge into develop
  js/page/detail.js
  js/page/profile.js
  js/page/review/reviewForm/writeReviewHandler.js
Labels: bug

#48 merge into develop
  js/page/review/reviewForm/writeReviewHandler.js
Labels: enhancement

#52 merge into develop
  css/page/detail.css
Labels: bug

#54 feat: footer 공통 적용
  css/common.css
  css/footer.css
  css/header.css
  css/page/review.css
  css/page/search-result.css
  css/page/subpage.css
  css/popup.css
  index.html
  js/common.js
  js/footer.js
  js/header.js
  page/detail.html
  page/nowplaying.html
  page/popular.html
  page/search-result.html
  page/search.html
  page/top20.html
  page/upcoming.html
Labels: enhancement

#55 feat: 팝업 이미지 변경
  img/common/popup-close.svg
  img/common/popup.jpg
  index.html
Labels: enhancement

#56 chore: 1.0.0
  css/common.css
  css/footer.css
  css/header.css
  css/page/review.css
  css/page/search-result.css
  css/page/subpage.css
  css/popup.css
  img/common/popup-close.svg
  img/common/popup.jpg
  index.html
  js/common.js
  js/footer.js
  js/header.js
  js/page/profile.js
  js/popup.js
  page/detail.html
  page/nowplaying.html
  page/popular.html
  page/profile.html
  page/search-result.html
  page/search.html
  page/top20.html
  page/upcoming.html
Labels: enhancement

#57 style: 카테고리 on
  img/common/popup.jpg
  page/nowplaying.html
  page/popular.html
  page/top20.html
  page/upcoming.html
Labels: enhancement

#58 chore: 1.0.1
  img/common/popup.jpg
  page/nowplaying.html
  page/popular.html
  page/top20.html
  page/upcoming.html
Labels: enhancement

#62 chore: 1.0.3
  css/footer.css
  img/detail/1713512289000104275.webp
  img/detail/detail_gra_bg.png
  img/detail/user.png
Labels: bug

#63 refactor: 완료 후 다시 이전 페이지로
  css/common.css
  css/page/detail.css
  css/page/search-result.css
  js/page/detail.js
  js/page/profile.js
  js/page/searchList.js
  page/detail.html
Labels: bug

#64 chore: 1.0.4
  css/common.css
  css/page/detail.css
  css/page/search-result.css
  js/page/detail.js
  js/page/profile.js
  js/page/searchList.js
  page/detail.html
Labels: bug

#65 fix: footer 에러 수정
  index.html
  js/footer.js
  page/detail.html
  page/nowplaying.html
  page/popular.html
  page/search-result.html
  page/search.html
  page/top20.html
  page/upcoming.html
Labels: bug

#66 chore: 1.0.4
  index.html
  js/footer.js
  page/detail.html
  page/nowplaying.html
  page/popular.html
  page/search-result.html
  page/search.html
  page/top20.html
  page/upcoming.html
Labels: bug

#67 doc: readme 업데이트
  README.md
Labels: documentation

#69 fix: 푸터 html 태그 수정
  page/detail.html
Labels: bug

#70 main into develop
  page/detail.html
Labels: bug

#71 Update README.md
  README.md
Labels: documentation

#72 Update README.md
  README.md
Labels: enhancement

#73 main into develop
  README.md
Labels: documentation

#74 fix: theme이 dom 그리기 전에 적용되게 한다
  css/reset.css
  index.html
  js/header.js
  js/theme.js
  page/detail.html
  page/nowplaying.html
  page/popular.html
  page/profile.html
  page/search-result.html
  page/search.html
  page/top20.html
  page/upcoming.html
Labels: bug

#75 main into develop
  css/reset.css
  index.html
  js/header.js
  js/theme.js
  page/detail.html
  page/nowplaying.html
  page/popular.html
  page/profile.html
  page/search-result.html
  page/search.html
  page/top20.html
  page/upcoming.html
Labels: enhancement

#76 refactor: module=type은 defer를 기본으로 가진다
  index.html
  page/detail.html
  page/nowplaying.html
  page/popular.html
  page/profile.html
  page/search-result.html
  page/search.html
  page/top20.html
  page/upcoming.html
Labels: duplicate

#78 fix: defer추가
  index.html
  page/profile.html
Labels: enhancement

#80 Update README.md
  README.md
Labels: documentation
